/**
    @file

    @brief
        SER25330 user library definitions

    @verbatim
    --------------------------------------------------------------------------
    This file and its contents are copyright (C) RTD Embedded Technologies,
    Inc.  All Rights Reserved.

    This software is licensed as described in the RTD End-User Software License
    Agreement.  For a copy of this agreement, refer to the file LICENSE.TXT
    (which should be included with this software) or contact RTD Embedded
    Technologies, Inc.
    --------------------------------------------------------------------------
    @endverbatim

    $Id: ser25330-library.h 156431 2026-07-31 15:19:12Z Nsmith $
*/

#ifndef SETTINGS_CONTROL_LIB__H
#define SETTINGS_CONTROL_LIB__H

// Defines the maximim number of ports supported per board.
#define SETTINGS_PORT_MAX 8

// Defines the lowest valid Revision Control value.
#define SETTINGS_REVISION_MIN 0

// Defines the highest valid Revision Control value.
#define SETTINGS_REVISION_MAX 1

// Defines the size, in bytes, of the area where the User Notes are stored.
#define SETTINGS_USER_NOTE_SIZE      0x10

/**
  @brief
  	Constants used for parsing command line parameters of example programs.
 */
enum Help_Options {
	/**
	 * @brief
	 *   Command line parameter --help
	 */
	HELP_OPTION = 1,

	/**
	 * @brief
	 *   Command line parameter --gpio
	 */
	GPIO_FILE_OPTION,

	/**
	 * @brief
	 *   Command line parameter --basetty
	 */
	TTY_FILE_OPTION
};

// Defines a structure that contains the User Notes and the Revision from the
//  settings.
typedef struct {
	unsigned char UserNotes[SETTINGS_USER_NOTE_SIZE];

	unsigned char RevisionControl;

} Settings_Info;

// Defines a structure that contains the Device ID and Revision information
// from the Exar chip
typedef struct {
	unsigned char device_rev;

	unsigned char device_id;
} Device_Info;

// Enumerates the possible mode settings for a port, including the needed bit
//  values.
typedef enum {
	// Represents a port mode of RS232.
	SETTINGS_PORT_MODE_RS232 = 0x7,

	// Represents a port mode of RS422.
	SETTINGS_PORT_MODE_RS422 = 0x0,

	// Represents a port mode of RS485.
	SETTINGS_PORT_MODE_RS485 = 0x3,

	// Represents a port mode of RS485 with RTS inverted.
	SETTINGS_PORT_MODE_RS485_RTS_INV = 0x1
} Settings_ModeType;

/*
    BEGIN Settings Control functions.
*/

/*
    Opens and prepares access to EEPROM-stored settings.

    file_handle - A valid, open handle to the first port on the Exar chip
        being accessed.
        
    device_handle - A device handle index for a gpio device. Depending on the
    driver, this value may be equivalent to the file_handle.

    Returns 1 on success and 0 otherwise.
*/
int Settings_Open(int file_handle, int *device_handle);

/*
    Closes access to EEPROM-stored settings. This causes the EPLD to read and
    apply the settings from the EEPROM.

    device_handle - A valid device handle , generated by Settings_Open
    
    Returns 1 on success and 0 otherwise.
*/
int Settings_Close(int device_handle);

/*
    Gets the Revision Control Byte and User Notes from the settings EEPROM.

    device_handle - A valid, open handle to the first port on the Exar chip
        being accessed.
    Info - A pointer to a location that will be filled with the information
        read from the EEPROM.

    Returns 1 on success and 0 otherwise.
*/
int Settings_GetInfo(int device_handle, Settings_Info * Info);

int Settings_GetUserNote0(int device_handle, Settings_Info * Info);
/*
    Sets the User Notes in the settings.

    device_handle - A valid, open handle to the first port on the Exar chip
        being accessed.
    Info - A pointer to a location that containing the User Notes information to
        write to the settings. Note that the Revision byte is not written and
        will be ignored.

    Returns 1 on success and 0 otherwise.
*/
int Settings_SetInfo(int device_handle, Settings_Info * Info);

/*
    Gets the Device ID and Revision information from the settings EEPROM.

    device_handle - A valid, open handle to the first port on the Exar chip
        being accessed.
    Info - A pointer to a location that will be filled with the information
        read from the EEPROM.

    Returns 1 on success and 0 otherwise.
*/
int Settings_GetDevInfo(int device_handle, Device_Info * Info);

/*
    Gets the current settings configuration for a single port.

    device_handle - A valid, open handle to the first port on the Exar chip
        being accessed.
    PortIndex - A one-based index of the port to get the configuration of.
    Mode - A pointer to a location that will be filled with the current mode
        setting of the selected port.
    TermEnabled - A pointer to a location that will be filled with TRUE if
        termination is enabled for the selected port, or FALSE if termination
        is disabled.

    Returns 1 on success and 0 otherwise.
*/
int Settings_GetPortConfig(int device_handle,
			   int PortIndex,
			   Settings_ModeType * Mode, int *TermEnabled);

/*
    Sets the settings configuration for a single port.

    device_handle - A valid, open handle to the first port on the Exar chip
        being accessed.
    PortIndex - A one-based index of the port to get the configuration of.
    Mode - The mode to set the select port to.
    EnableTerm - Pass in TRUE to enable termination for the selected port, or
        FALSE to disable termination.

    Returns 1 on success and 0 otherwise.
*/
int Settings_SetPortConfig(int device_handle,
			   int PortIndex,
			   Settings_ModeType Mode, int EnableTerm);

/*
    END Settings Control functions.
*/

/*
   BEGIN other MPIO functions.
*/

/*
    Reads the 4 bits making up the User ID Jumper field.

    device_handle - A valid, open handle to the first port on the Exar chip
        being accessed.
    Value - A pointer to a location which will be filled with the byte read from the high
        order MPIO bits containing the User ID Jumper value.

    Returns TRUE on success and FALSE otherwise or if unsupported.
*/
int MPIO_ReadUserIdJumper(int device_handle, unsigned char *Value);

/*
  END other MPIO functions.
*/

#endif
